server:
  port: 8888


spring:
  datasource:
    url: ${JAVA_COURSE_DB_URL}
    username: ${JAVA_COURSE_DB_USER}
    password: ${JAVA_COURSE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
     change-log: db/changelog/db-changelog-master.yaml
     default-schema: chat

jwt:
  secret-key: ${JAVA_COURSE_JWT_KEY}

logging:
  level:
    org:
      springframework:
        security=DEBUG:





